# Generated by Django 4.1.2 on 2022-11-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Influenceur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=1)),
                ("nationality", models.CharField(max_length=200)),
                ("nbr_followers", models.IntegerField(default=0)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("theme", models.CharField(max_length=200)),
                ("experience", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=300)),
            ],
        ),
    ]
